[package]
name = "s3cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.X"
s3cli_lib = { path = "../s3cli_lib"}
base64 = "0.X"
chacha20 = "0.9.X"
sha2 = "0.X"
serde-xml-rs = "0.7.1"
serde = { version = "1.X", features = ["derive"] }